sudo: required
os: linux
language: minimal
addons:
  apt:
    packages:
    - docker-ce
git:
  depth: 4
services:
  - docker

before_install:
  - docker pull lacledeslan/gamesvr-goldsource

script:
  - docker version
  - docker build --no-cache --tag lacledeslan/gamesvr-goldsource-tfc --build-arg BUILDNODE=TravisCI --build-arg SOURCE_COMMIT="$TRAVIS_COMMIT" -f linux.Dockerfile .
  - docker run -it --rm lacledeslan/gamesvr-goldsource-tfc ./ll-tests/gamesvr-goldsource.tfc.sh

before_deploy:
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin;
deploy:
  provider: script
  script: docker push lacledeslan/gamesvr-goldsource-tfc
  on:
    branch: master
after_deploy:
  - curl -X POST https://hooks.microbadger.com/images/lacledeslan/gamesvr-goldsource/$MICROBADGER_TOKEN
