name: Update Docker Hub Description

on:
  push:
    branches: [ master ]

jobs:
  update-dockerhub-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Docker HUB Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: lacledeslan/gamesvr-hl2dm-freeplay
          short-description: "Laclede's LAN Team Fortress Classic Freeplay Server"
          readme-filepath: ./README.md
